spring:
  datasource:
    url: jdbc:hsqldb:file:D:\\database.txt
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  data:
    rest:
      basePath: /api
      pageParamName: p
      limitParamName: l
      sortParamName: s
      defaultPageSize: 10
      maxPageSize: 100
  clients:
    web:
      clientId: web
      clientSecret: web
      authorizedGrantTypes: password,refresh_token
      scope: user